# Generated by Django 3.2.6 on 2021-08-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=127)),
                ('cpf', models.TextField(max_length=11)),
                ('adress', models.TextField(max_length=127)),
                ('age', models.PositiveIntegerField(max_length=3)),
                ('ticket_id', models.CharField(max_length=5)),
                ('aproved', models.BooleanField),
            ],
        ),
    ]
